module.exports = {
    SESSION_ID: process.env.SESSION_ID || '',
    CREDS_JSON: process.env.CREDS_JSON || '',
    MONGO_URI: process.env.MONGO_URI || 'mongodb+srv://lakshan:12345lakshan@cluster0.k6w7ris.mongodb.net/',
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/JBIQDUg6f7g5AvExseAzO4?mode=hqctcla',
    ADMIN_LIST_PATH: './admin.json',
    RCD_IMAGE_PATH: 'https://whiteshadow-uploder.zone.id/files/13z.jpg',
    NEWSLETTER_JID: '120363421928318889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'lakshan md',
    OWNER_NAME: 'lakshan',

    OWNER_NUMBER: '94783314361',

    BOT_VERSION: '1.0.0',
    BOT_FOOTER: 'lakshan md',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbAWcvCLY6dAjn0FnW0L',
};
